twitch:
  bot-name: "NickInTwitch"
  irc-token: "Token" #Chat OAuth token without: "oauth:"
  api-token: "Token" #[Otional] Twitch API Kraken Token 
  channel: "ChannelForUseBot"
settings:
  web:
    enabled: True
    tcp_port: 8080
    ssl:
      enabled: True
      tcp_port: 8443
  logging:
    live: True
    file: False
